### ISSUE TITLE
QUestion on Active directory settings  for Broadsea 3.0 

### ISSUE THREAD

**Issue by gkowalski** [OHDSI/Broadsea#76]
Is there documentation on the AD Settings to be used ?  

# AD
SECURITY_AUTH_AD_ENABLED="true"
SECURITY_AD_URL="ldap://server.net:389"
SECURITY_AD_SEARCHBASE="dc=domain,dc=net"
SECURITY_AD_PRINCIPALSUFFIX="ou=Service Accounts,dc=domain,dc=net"
SECURITY_AD_SYSTEM_USERNAME="username"
SECURITY_AD_SYSTEM_PASSWORD="passwd"
SECURITY_AD_SEARCHFILTER="(&amp;(objectClass=person)(cn=%s))"
SECURITY_AD_IGNORE_PARTIAL_RESULT_EXCEPTION="true"
SECURITY_AD_RESULT_COUNT_LIMIT="10000"
SECURITY_AD_DEFAULT_IMPORT_GROUP="public"
SECURITY_AD_SEARCHSTRING="(&amp;(objectClass=person)(userPrincipalName=%s))"
SECURITY_AD_USERMAPPING_DISPLAYNAMEATTR="displayName"
SECURITY_AD_USERMAPPING_FIRSTNAMEATTR="givenname"
SECURITY_AD_USERMAPPING_MIDDLENAMEATTR="initials"
SECURITY_AD_USERMAPPING_LASTNAMEATTR="sn"
SECURITY_AD_USERMAPPING_USERNAMEATTR="sAMAccountName"
SECURITY_AD_USERIMPORT_LOGINATTR="sAMAccountName"
SECURITY_AD_USERIMPORT_USERNAMEATTR="cn"

what is the difference between SECURITY_AD_SEARCHBASE and SECURITY_AD_SEARCHFILTER ? 

is SECURITY_AD_PRINCIPALSUFFIX only used for the initial bind of the SECURITY_AD_SYSTEM_USERNAME user ? 

is the SECURITY_AD_URL still "ldap://...." ? 

Thanks 

George

**Comment by gkowalski** [comment]
A follow up question , how to increase the logging level so I get more than just : 
```
com.odysseusinc.logging.LoggingService - [] - Log in failed for user login xxx
```

**Comment by alondhe** [comment]
Hi @gkowalski -- good questions, I've raised follow up issues on each.

**Comment by gkowalski** [comment]
I was thinking of installing the WEBAPI app separately to start hacking the log4j settings and seeing if I can get the logging to spit out what I want.

**Comment by gkowalski** [comment]
Well I did find a way to increase logging  with Broadsea by setting the application.properties , but  it didn't really help in my instance . Procedure is : 

- First copied the application.properties out of the container to my local machine 
``` 
$ docker cp ohdsi-webapi:/var/lib/ohdsi/webapi/WEB-INF/classes/application.properties .
```
Then edit this properties file and change line 13 to end in "all" from "info" : 
```
logging.level.org.apache.shiro=all
```
all is the keyword , just log all the things !

Then edit the docker-compose.yml file to mount ( override ) this file into the container  by adding the "volumns:" section below into the ohdsi-webapi-from-image section  : 

```
  # WebAPI and Atlas services based on the standard Docker Hub images -------------
  ohdsi-webapi-from-image:
    profiles: [ "default", "webapi-from-image" ]
    image: docker.io/ohdsi/webapi:latest
    volumes:
            - ${PWD}/application.properties:/var/lib/ohdsi/webapi/WEB-INF/classes/application.properties
    extends:
      file: "ohdsi-webapi.yml"
      service: ohdsi-webapi
```
finally restart your containers with the normal 
```docker compose --profile default up -d```

Now watch the logs while you log in : 
```
docker logs ohdsi-webapi
```

shows the following : 

```
2023-05-04 01:13:15.413 TRACE http-nio-8080-exec-6 org.apache.shiro.util.ThreadContext - [] - Retrieved value of type [org.ohdsi.webapi.shiro.subject.WebDelegatingRunAsSubject] for key [org.apache.shiro.util.ThreadContext_SUBJECT_KEY] bound to thread [http-nio-8080-exec-6]
2023-05-04 01:13:15.413 TRACE http-nio-8080-exec-6 org.apache.shiro.subject.support.DelegatingSubject - [] - attempting to get session; create = false; session is null = true; session has id = false
2023-05-04 01:13:15.413 TRACE http-nio-8080-exec-6 org.apache.shiro.authc.AbstractAuthenticator - [] - Authentication attempt received for token [org.ohdsi.webapi.shiro.tokens.ActiveDirectoryUsernamePasswordToken - gkowalsk, rememberMe=false]
2023-05-04 01:13:15.416 TRACE http-nio-8080-exec-6 org.apache.shiro.authc.pam.ModularRealmAuthenticator - [] - Iterating through 4 realms for PAM authentication
2023-05-04 01:13:15.416 DEBUG http-nio-8080-exec-6 org.apache.shiro.authc.pam.ModularRealmAuthenticator - [] - Realm [org.ohdsi.webapi.shiro.realms.JwtAuthRealm@301434fb] does not support token org.ohdsi.webapi.shiro.tokens.ActiveDirectoryUsernamePasswordToken - gkowalsk, rememberMe=false.  Skipping realm.
2023-05-04 01:13:15.418 DEBUG http-nio-8080-exec-6 org.apache.shiro.authc.pam.ModularRealmAuthenticator - [] - Realm [waffle.shiro.negotiate.NegotiateAuthenticationRealm@23f16852] does not support token org.ohdsi.webapi.shiro.tokens.ActiveDirectoryUsernamePasswordToken - gkowalsk, rememberMe=false.  Skipping realm.
2023-05-04 01:13:15.418 DEBUG http-nio-8080-exec-6 org.apache.shiro.authc.pam.ModularRealmAuthenticator - [] - Realm [io.buji.pac4j.realm.Pac4jRealm@30a8ac50] does not support token org.ohdsi.webapi.shiro.tokens.ActiveDirectoryUsernamePasswordToken - gkowalsk, rememberMe=false.  Skipping realm.
2023-05-04 01:13:15.418 TRACE http-nio-8080-exec-6 org.apache.shiro.authc.pam.ModularRealmAuthenticator - [] - Attempting to authenticate token [org.ohdsi.webapi.shiro.tokens.ActiveDirectoryUsernamePasswordToken - gkowalsk, rememberMe=false] using realm [org.ohdsi.webapi.shiro.realms.ADRealm@1ee04ff6]
2023-05-04 01:13:15.418 DEBUG http-nio-8080-exec-6 org.apache.shiro.realm.ldap.AbstractLdapRealm - [] - No LdapContextFactory specified - creating a default instance.
2023-05-04 01:13:15.456 DEBUG http-nio-8080-exec-6 org.apache.shiro.authc.pam.ModularRealmAuthenticator - [] - Realm [org.ohdsi.webapi.shiro.realms.ADRealm@1ee04ff6] threw an exception during a multi-realm authentication attempt:
org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563]
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:191) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:355) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.support.AbstractContextSource.doGetContext(AbstractContextSource.java:139) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.support.AbstractContextSource.getReadOnlyContext(AbstractContextSource.java:158) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:357) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:328) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:604) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:594) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:482) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:498) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.ohdsi.webapi.shiro.realms.ADRealm.queryForAuthenticationInfo(ADRealm.java:83) ~[classes/:?]
	at org.apache.shiro.realm.ldap.AbstractLdapRealm.doGetAuthenticationInfo(AbstractLdapRealm.java:212) ~[shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571) ~[shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:225) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:275) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.ohdsi.webapi.shiro.lockout.LockoutWebSecurityManager.login(LockoutWebSecurityManager.java:66) [classes/:?]
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.filter.authc.AuthenticatingFilter.executeLogin(AuthenticatingFilter.java:53) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.ohdsi.webapi.shiro.filters.auth.AbstractLdapAuthFilter.onAccessDenied(AbstractLdapAuthFilter.java:60) [classes/:?]
	at org.apache.shiro.web.filter.AccessControlFilter.onAccessDenied(AccessControlFilter.java:133) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:223) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:198) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.ohdsi.webapi.shiro.filters.ResponseNoCacheFilter.doFilter(ResponseNoCacheFilter.java:26) [classes/:?]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:147) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) [shiro-core-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [shiro-web-1.10.1.jar!/:1.10.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.ohdsi.webapi.shiro.filters.CacheFilter.doFilter(CacheFilter.java:35) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.ohdsi.webapi.shiro.filters.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
Caused by: javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563]
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3261) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3207) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2993) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2907) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:347) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154) ~[?:1.8.0_342]
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84) ~[?:1.8.0_342]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:695) ~[?:1.8.0_342]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[?:1.8.0_342]
	at javax.naming.InitialContext.init(InitialContext.java:244) ~[?:1.8.0_342]
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154) ~[?:1.8.0_342]
	at org.springframework.ldap.core.support.LdapContextSource.getDirContextInstance(LdapContextSource.java:42) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:343) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	... 94 more
2023-05-04 01:13:15.464 DEBUG http-nio-8080-exec-6 org.apache.shiro.authc.AbstractAuthenticator - [] - Authentication successful for token [org.ohdsi.webapi.shiro.tokens.ActiveDirectoryUsernamePasswordToken - gkowalsk, rememberMe=false].  Returned account [[!!!org.apache.shiro.authc.SimpleAuthenticationInfo@406ac269=>java.lang.NullPointerException:null!!!]]
2023-05-04 01:13:15.464 TRACE http-nio-8080-exec-6 org.apache.shiro.web.servlet.SimpleCookie - [] - calculated path: /WebAPI
2023-05-04 01:13:15.465 DEBUG http-nio-8080-exec-6 org.apache.shiro.web.servlet.SimpleCookie - [] - Added HttpServletResponse Cookie [rememberMe=deleteMe; Path=/WebAPI; Max-Age=0; Expires=Wed, 03-May-2023 01:13:15 GMT; SameSite=lax]
2023-05-04 01:13:15.465 TRACE http-nio-8080-exec-6 org.apache.shiro.web.servlet.SimpleCookie - [] - Removed 'rememberMe' cookie by setting maxAge=0
2023-05-04 01:13:15.466 INFO http-nio-8080-exec-6 com.odysseusinc.logging.LoggingService - [] - Log in failed for user login = gkowalsk
```
Odd it says Authentication successful for token .. then "Log in failed for user login = gkowalsk" . My user is in the LOGIN_ACCOUNT table with EXTERNAL_AUTH set to true 

<img width="381" alt="image" src="https://user-images.githubusercontent.com/617805/236085298-962caa6b-bc9f-4c95-9135-e69e509a8136.png">

**Comment by gkowalski** [comment]
AcceptSecurityContext error, data 52e is a common , password is incorrect error.  Was hopping  it logged its connection params when it attempting to connect to the AD Server. May need to get my IT Staff involved to see what's being sent in their logs.
